### ISSUE TITLE
gSnap will no longer enable

### ISSUE THREAD

**Issue by SamKingDev** [GnomeSnapExtensions/gSnap#40] opened 2022-09-28 08:14 UTC
I turned on my PC today and for some reason gSnap won't enable. It just gives the following error:

`this.layouts.workspaces[currentWorkspaceIdx][m.index] is undefined`

I'm running the latest version of PopOS 22.04

**Comment by meronz** [comment] 2022-11-20 10:47
Hi! Thanks for opening an issue, and sorry for the response delay. Do you still have this problem and the related logs + **layouts.json** file? Otherwise it will be impossible to replicate!

**Comment by SamKingDev** [comment] 2022-11-21 09:39
This feature comes and goes, where are the logs and layouts.json file stored?

**Comment by meronz** [comment] 2022-11-21 18:13
Both is written in the README.

**Comment by rsaffi** [comment] 2022-12-09 21:39
@meronz Since @SamKingDev hasn't replied in 18 days, let me provide some further info, since I also face the same error: 

> this.layouts.workspaces[currentWorkspaceIdx][m.index] is undefined

I'm running Manjaro 22.0.0 (it's a rolling distro, but I confirm everything is up-to-date as of today, 2022-12-09), Gnome version is `43.1`.

A few notes (with the attached files as requested):

1. Ever since I first installed the extension, I could never enable it due to the exact error quoted above, so I never got to actually edit/change the layouts, so the attached one is the one that was there after installing the extension for the first time.

[layouts.json.gz](https://github.com/GnomeSnapExtensions/gSnap/files/10198247/layouts.json.gz)

2. I have an unconventional display setup, so I also wonder if that could play a part into the problem. Display setup shown in the image below.

![Screenshot from 2022-12-09 22-25-14](https://user-images.githubusercontent.com/15200226/206798618-e4d1ce13-2b24-4ea1-bba1-e59794eec306.png)

3. And here are the logs. I forced them being generated new by removing the extension and re-installing it. After reinstallation the error was already being displayed on the Extensions application on Gnome.

[gSnap.log.gz](https://github.com/GnomeSnapExtensions/gSnap/files/10198271/gSnap.log.gz)

**Comment by meronz** [comment] 2022-12-18 10:23
> Also, my workspace settings in Gnome "Multitasking" is set for 3 fixed workspaces and only on the primary display (the one in the middle from the image below).

Oh. I wonder if this could be related to that. I'll check this as soon as possible.

**Comment by meronz** [comment] 2022-12-24 14:11
I reproduced this bug by enabling the "Workspaces on primary display only" setting, and logging out. I triaged it and created a pull request that should fix it. Could you try if this works for you? I'll wait before merging it.

**Comment by rsaffi** [comment] 2022-12-24 15:31
@meronz Had to install `typescript` and `rollup`, but after doing that I still got this when running `npm run install-extension` from the `issues/40` branch:

```bash
Sa Dez 24 16:29:36 ricardo@viserion [0] ~/git/github/gSnap  (issues/40)
$ npm run install-extension 

> gsnap@0.0.1 install-extension
> npm run build && sh install-extension.sh


> gsnap@0.0.1 build
> tsc && rollup --config rollup.config.js

(node:3205996) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
[!] RollupError: Node tried to load your configuration file as CommonJS even though it is likely an ES module. To resolve this, change the extension of your configuration to ".mjs", set "type": "module" in your package.json file or pass the "--bundleConfigAsCjs" flag.

Original error: Cannot use import statement outside a module
https://rollupjs.org/guide/en/#--bundleconfigascjs
/home/ricardo/git/github/gSnap/rollup.config.js:1
import { defineConfig } from 'rollup';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:74:18)
    at wrapSafe (node:internal/modules/cjs/loader:1141:20)
    at Module._compile (node:internal/modules/cjs/loader:1182:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

As I'm neither a nodejs nor typescript guy, I'll need some further instructions from you! >.<

**Comment by meronz** [comment] 2022-12-24 15:55
Ok, maybe the docs are lacking on this side.
Try running `npm ci` before the install-extension

**Comment by rsaffi** [comment] 2022-12-25 18:49
Ok, that did the trick and it installed. I logged off and back in and saw that the extension was working, but I have a follow-up question: I set up the layouts as (in this order):

* Monitor 0 (left): 1 column (I actually wanted 2 _rows_, but haven't figured out how to do rows yet)
* Monitor 1 (right): 2 columns
* Monitor 2 (center): 3 column (focused)

I noticed that gSnap respected the choice for Monitors 0 and 2, but on monitor 1 it screwed up the layout the moment I set the center one as "3 column (focused)".

This is what happened:

![image](https://user-images.githubusercontent.com/15200226/209479090-b87a57d6-c51a-4b98-9b02-9118e5a4bdef.png)

**Comment by meronz** [comment] 2022-12-26 07:21
So, if I understood that correctly, the bug is that the extension allows for percentages to be set to more than 100%?
Does this make the extension unusable for you?

**Comment by rsaffi** [comment] 2022-12-26 13:33
No, it's not about that, but perhaps I failed to explain in a clearer manner. It's just that I am unable to setup a layout that is respecting the monitor's boundaries. And also if you look at the second screenshot from my previous message the zone on the right monitor does not go all the way to the right edge.

**Comment by meronz** [comment] 2022-12-26 14:23
Ok, I'll try to replicate and fix this. Sorry if I did not understand before, I can see now the problem.

**Comment by meronz** [comment] 2022-12-27 09:47
I should have fixed it in the linked PR (#54). Try to build it to see if it works for you.

**Comment by rsaffi** [comment] 2022-12-29 12:11
Hi @meronz, thanks for the feedback! Just tested the branch `issues/editor-fixes` and everything is working perfectly! 
Thanks for the great work and effort you put into getting these addressed! 💪🏻 

![Screenshot from 2022-12-29 13-10-00](https://user-images.githubusercontent.com/15200226/209949478-85bd9519-fcb6-476a-8e1e-c1631b265040.png)

**Comment by meronz** [comment] 2022-12-29 12:26
You're welcome. The merge in main will need some time though, since I'm working these holidays.

**Comment by meronz** [comment] 2022-12-30 19:54
Merged! I'll try to release on extensions.gnome.org ASAP.

**Closed by meronz** 2022-12-30 19:54 UTC
Labels: bug
