### ISSUE TITLE
Feature Request: Allow ctrl to be changed to another button

### ISSUE THREAD

**Issue by asafarevich** [GnomeSnapExtensions/gSnap#70] opened 2023-06-28 19:34 UTC
In settings currently ctrl is used to snap to window... Would love ability to change that to ALT or Windows key. On my keyboard they are easier to press.

**Comment by bmaupin** [comment] 2023-08-02 14:40
This looks like a possible duplicate of #30

**Closed** 2023-08-02 15:36 UTC
